"""empty message

Revision ID: 1133257adb7c
Revises: eb2306631ba5
Create Date: 2023-11-14 14:23:18.356981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1133257adb7c'
down_revision = 'eb2306631ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence_vocab', schema=None) as batch_op:
        batch_op.drop_constraint('sentence_vocab_sentence_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sentences', ['sentence_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence_vocab', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sentence_vocab_sentence_id_fkey', 'sentences', ['sentence_id'], ['id'])

    # ### end Alembic commands ###
