"""empty message

Revision ID: eb2306631ba5
Revises: 97a0883f56a9
Create Date: 2023-11-13 21:15:29.102474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2306631ba5'
down_revision = '97a0883f56a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence_upvotes', schema=None) as batch_op:
        batch_op.drop_constraint('sentence_upvotes_sentence_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sentence_upvotes_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sentences', ['sentence_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence_upvotes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sentence_upvotes_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('sentence_upvotes_sentence_id_fkey', 'sentences', ['sentence_id'], ['id'])

    # ### end Alembic commands ###
